version: "3"
services:
  db:
    image: postgres:9.6.18-alpine
    ports:
      - 15432:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - database:/var/lib/postgresql/data/
  app:
    build:
      context: .
      args:
        BUNDLE_PATH: /usr/local/bundle
    env_file: .env
    environment:
      - BUNDLE_PATH=/usr/local/bundle
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  database:
  bundle:
  node_modules:
